//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIFlowWndAIR_WaringRes.c"
#include "UIFlowWndAIR_Waring.h"
#include "UIFlow.h"
//---------------------UIFlowWndAIR_WaringCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndAIR_Waring)
CTRL_LIST_ITEM(UIFlowWndAIR_PW25_value)
CTRL_LIST_ITEM(UIFlowWndAIR_Quality)
CTRL_LIST_ITEM(UIFlowWndAIR_DetTime_value)
CTRL_LIST_ITEM(UIFlowWndAIR_Tab)
CTRL_LIST_END

//----------------------UIFlowWndAIR_WaringCtrl Event---------------------------
INT32 UIFlowWndAIR_Waring_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndAIR_Waring_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndAIR_Waring_OnTimer(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIFlowWndAIR_Waring)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIFlowWndAIR_Waring_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIFlowWndAIR_Waring_OnClose)
EVENT_ITEM(NVTEVT_TIMER,UIFlowWndAIR_Waring_OnTimer)
EVENT_END
static UINT32  gAirDetTimerID = NULL_TIMER;

static int DetTimeCnt = 0;

#define PM25_40_MID  75//40
#define PM25_2000_HIGH  150//200
 
static BOOL AIR_WINDOW_OpenStatus = FALSE;
BOOL GetAIR_WINDOW_OpenStatus(void)
{
    return AIR_WINDOW_OpenStatus;
}
int CheackAIR_QualityLVL(UINT32 data)
{
    int ret = 0;
    if(data <= PM25_40_MID)
        ret = 0;
    else if(data <= PM25_2000_HIGH)
        ret = 1;
    else if(data > PM25_2000_HIGH)
        ret = 2;
        return ret;
}

void ShowAIR_Quality(UINT32 data)
{
if(data != 0)
        {
    if(Get_AIR_LINKSTATUS())
    UxState_SetData(&UIFlowWndAIR_QualityCtrl,STATE_CURITEM,CheackAIR_QualityLVL(data));
    }
}

static CHAR    g_PW25_valueStr[20] = {0};
void ShowPW25_value(UINT32 data)
{
    UINT32 Temp=0;
    if(data != 0)
   {
    sprintf(g_PW25_valueStr,"%d",data );
    if(Get_AIR_LINKSTATUS())
    UxStatic_SetData(&UIFlowWndAIR_PW25_valueCtrl,STATIC_VALUE,Txt_Pointer(g_PW25_valueStr));
   }
    else
    {
    sprintf(g_PW25_valueStr,"%d",Temp );
    if(Get_AIR_LINKSTATUS())
    UxStatic_SetData(&UIFlowWndAIR_PW25_valueCtrl,STATIC_VALUE,Txt_Pointer(g_PW25_valueStr));

    }
}

static CHAR    g_DetTimeStr[20] = {0};
void ShowDetTime(UINT32 data)
{
    UxCtrl_SetShow(&UIFlowWndAIR_DetTime_valueCtrl,FALSE);
    //sprintf(g_DetTimeStr,"%02d:%02d",data/3600,(data%3600)/60);
    //sprintf(g_DetTimeStr,"%04d",data/60);
    sprintf(g_DetTimeStr,"%04d",data/(60*5));
    UxStatic_SetData(&UIFlowWndAIR_DetTime_valueCtrl,STATIC_VALUE,Txt_Pointer(g_DetTimeStr));
    UxCtrl_SetShow(&UIFlowWndAIR_DetTime_valueCtrl,TRUE);
}

void ShowSPEED_WIN(UINT32 data)
{
if(data != 0)
        {
    if(Get_AIR_LINKSTATUS())
        {
        if(data <= PM25_40_MID)
            {
            UxTab_SetData(&UIFlowWndAIR_TabCtrl, TAB_FOCUS, 2);
            
             
            }
        else if(data <= PM25_2000_HIGH)
            {
            UxTab_SetData(&UIFlowWndAIR_TabCtrl, TAB_FOCUS, 1);
            }
        else if(data > PM25_2000_HIGH)
            {
            UxTab_SetData(&UIFlowWndAIR_TabCtrl, TAB_FOCUS, 0);
            }
        }
}
    
}

INT32 UIFlowWndAIR_Waring_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    DetTimeCnt = 0;
    ShowAIR_Quality(Get_PM_Data());
    ShowPW25_value(Get_PM_Data());
    ShowDetTime(DetTimeCnt);
    ShowSPEED_WIN(Get_PM_Data());
    AIR_WINDOW_OpenStatus = TRUE;

    if (gAirDetTimerID==NULL_TIMER)
    {
        gAirDetTimerID = GxTimer_StartTimer(200, NVTEVT_01SEC_TIMER, CONTINUE);
    }
    
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndAIR_Waring_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    AIR_WINDOW_OpenStatus = FALSE;
    if(UI_GetData(FL_LCDOFF ) == LCDOFF_ON)
    GxCustom_SetControl(GXCUSTOM_CTRL_AUTOLCDOFF_EN, FALSE);
    else
        GxCustom_SetControl(GXCUSTOM_CTRL_AUTOLCDOFF_EN, TRUE);
     if (gAirDetTimerID!=NULL_TIMER)
    {
        GxTimer_StopTimer(&gAirDetTimerID);
    }
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}

INT32 UIFlowWndAIR_Waring_OnTimer(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32  uiEvent;
    uiEvent = paramNum ? paramArray[0] : 0;
    
    switch(uiEvent)
    {
    case NVTEVT_01SEC_TIMER:
        AIR_WINDOW_OpenStatus = TRUE;
        ShowAIR_Quality(Get_PM_Data());
        ShowPW25_value(Get_PM_Data());
        ShowDetTime(DetTimeCnt);
        ShowSPEED_WIN(Get_PM_Data());
        DetTimeCnt++;
        break;
    }
    Ux_DefaultEvent(pCtrl,NVTEVT_TIMER,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
//----------------------UIFlowWndAIR_PW25_valueCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndAIR_PW25_value)
EVENT_END

//----------------------UIFlowWndAIR_QualityCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndAIR_Quality)
EVENT_END

//----------------------UIFlowWndAIR_DetTime_valueCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndAIR_DetTime_value)
EVENT_END

//----------------------UIFlowWndAIR_TabCtrl Event---------------------------
INT32 UIFlowWndAIR_Tab_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndAIR_Tab_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndAIR_Tab_OnKeyLeft(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndAIR_Tab_OnKeyRight(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIFlowWndAIR_Tab)
EVENT_ITEM(NVTEVT_KEY_UP,UIFlowWndAIR_Tab_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIFlowWndAIR_Tab_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_LEFT,UIFlowWndAIR_Tab_OnKeyLeft)
//ENT_ITEM(NVTEVT_KEY_RIGHT,UIFlowWndAIR_Tab_OnKeyRight)
EVENT_ITEM(NVTEVT_KEY_MENU,UIFlowWndAIR_Tab_OnKeyRight)
EVENT_END

INT32 UIFlowWndAIR_Tab_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndAIR_Tab_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndAIR_Tab_OnKeyLeft(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    //_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndAIR_Tab_OnKeyRight(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_CloseWindow((VControl *)(&UIFlowWndAIR_WaringCtrl), 0);
    //_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    return NVTEVT_CONSUME;
}
//----------------------UIFlowWndAIR_HIGH_SPEED_WINCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndAIR_HIGH_SPEED_WIN)
EVENT_END

//----------------------UIFlowWndAIR_MID_SPEED_WINCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndAIR_MID_SPEED_WIN)
EVENT_END

//----------------------UIFlowWndAIR_LOW_SPEED_WINCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndAIR_LOW_SPEED_WIN)
EVENT_END
