//This source code is generated by UI Designer Studio.

#ifndef UIFLOWWNDAIR_WARING_H
#define UIFLOWWNDAIR_WARING_H

#include "UIFramework.h"

extern VControl UIFlowWndAIR_WaringCtrl;//Panel type 

extern VControl UIFlowWndAIR_PW25_valueCtrl;//Static type 

extern VControl UIFlowWndAIR_QualityCtrl;//Status type 

typedef enum
{
UIFlowWndAIR_Quality_ICON_AIR_PM_GOOD,
UIFlowWndAIR_Quality_ICON_AIR_PM_NORMAL,
UIFlowWndAIR_Quality_ICON_AIR_PM_BAD,
UIFlowWndAIR_Quality_MAX
}UIFlowWndAIR_Quality_Setting;

extern VControl UIFlowWndAIR_DetTime_valueCtrl;//Static type 

extern VControl UIFlowWndAIR_TabCtrl;//Tab type 

typedef enum
{
UIFlowWndAIR_Tab_UIFlowWndAIR_HIGH_SPEED_WIN,
UIFlowWndAIR_Tab_UIFlowWndAIR_MID_SPEED_WIN,
UIFlowWndAIR_Tab_UIFlowWndAIR_LOW_SPEED_WIN,
UIFlowWndAIR_Tab_MAX
}UIFlowWndAIR_Tab_Setting;

extern VControl UIFlowWndAIR_HIGH_SPEED_WINCtrl;//Button type 

extern VControl UIFlowWndAIR_MID_SPEED_WINCtrl;//Button type 

extern VControl UIFlowWndAIR_LOW_SPEED_WINCtrl;//Button type 

#endif
