//This source code is generated by UI Designer Studio.
#ifdef __ECOS
#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "NVTToolCommand.h"
#include "UIMenuWndWiFiModuleLinkRes.c"
#include "UIFlow.h"
#include "UIAppNetwork.h"
#include "WifiAppCmd.h" 
extern UIMenuStoreInfo  currentInfo;
extern BOOL g_bgsensor;

//---------------------UIMenuWndWiFiModuleLinkCtrl Debug Definition -----------------------------
#define _UIMENUWNDWIFIMODULELINK_ERROR_MSG        1
#define _UIMENUWNDWIFIMODULELINK_TRACE_MSG        0

#if (_UIMENUWNDWIFIMODULELINK_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define UIMenuWndWiFiModuleLinkErrMsg(...)            debug_msg ("^R UIMenuWndWiFiModuleLink: "__VA_ARGS__)
#else
#define UIMenuWndWiFiModuleLinkErrMsg(...)
#endif

#if (_UIMENUWNDWIFIMODULELINK_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define UIMenuWndWiFiModuleLinkTraceMsg(...)          debug_msg ("^B UIMenuWndWiFiModuleLink: "__VA_ARGS__)
#else
#define UIMenuWndWiFiModuleLinkTraceMsg(...)
#endif

//---------------------UIMenuWndWiFiModuleLinkCtrl Global Variables -----------------------------
//---------------------UIMenuWndWiFiModuleLinkCtrl Prototype Declaration  -----------------------

//---------------------UIMenuWndWiFiModuleLinkCtrl Public API  ----------------------------------

//---------------------UIMenuWndWiFiModuleLinkCtrl Private API  ---------------------------------
void UIMenuWndWiFiModuleLink_UpdateData(void);

//---------------------UIMenuWndWiFiModuleLinkCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndWiFiModuleLink)
CTRL_LIST_ITEM(UIMenuWndWiFiModuleLink_StaticICN_WiFi)
CTRL_LIST_ITEM(UIMenuWndWiFiModuleLink_StaticICN_TitleBar)
CTRL_LIST_ITEM(UIMenuWndWiFiModuleLink_StatusTXT_WiFiMode)
CTRL_LIST_ITEM(UIMenuWndWiFiModuleLink_StaticTXT_SSID)
CTRL_LIST_ITEM(UIMenuWndWiFiModuleLink_StaticTXT_Key)
CTRL_LIST_ITEM(UIMenuWndWiFiModeLink_Tab_RefreshAndWiFiOff)
CTRL_LIST_END

//----------------------UIMenuWndWiFiModuleLinkCtrl Event---------------------------
INT32 UIMenuWndWiFiModuleLink_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiModuleLink_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiModuleLink_OnChildClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiModuleLink_OnBattery(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiModuleLink_OnTimer(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiModuleLink_OnMovieFull(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiModuleLink_OnMovieWrError(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiModuleLink_OnStorageSlow(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLink_OnKeyShutter2(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLink_OnGsensor(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLink_OnKeyUP(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLink_OnMovieOneSec(VControl *, UINT32, UINT32 *);

EVENT_BEGIN(UIMenuWndWiFiModuleLink)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndWiFiModuleLink_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndWiFiModuleLink_OnClose)
EVENT_ITEM(NVTEVT_CHILD_CLOSE,UIMenuWndWiFiModuleLink_OnChildClose)
EVENT_ITEM(NVTEVT_BATTERY,UIMenuWndWiFiModuleLink_OnBattery)
EVENT_ITEM(NVTEVT_TIMER,UIMenuWndWiFiModuleLink_OnTimer)
EVENT_ITEM(NVTEVT_CB_MOVIE_OVERTIME,UIMenuWndWiFiModuleLink_OnMovieFull) // the same handling as storage full (may need to show special message)
EVENT_ITEM(NVTEVT_CB_MOVIE_FULL,UIMenuWndWiFiModuleLink_OnMovieFull)
EVENT_ITEM(NVTEVT_CB_MOVIE_LOOPREC_FULL,UIMenuWndWiFiModuleLink_OnMovieFull)
EVENT_ITEM(NVTEVT_CB_MOVIE_WR_ERROR,UIMenuWndWiFiModuleLink_OnMovieWrError)
EVENT_ITEM(NVTEVT_CB_MOVIE_SLOW,UIMenuWndWiFiModuleLink_OnStorageSlow)
EVENT_ITEM(NVTEVT_KEY_SHUTTER2,UIMenuWndWiFiMobileLink_OnKeyShutter2)
//EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndWiFiMobileLink_OnKeyUP)
EVENT_ITEM(NVTRET_PROTECT,UIMenuWndWiFiMobileLink_OnGsensor)
EVENT_ITEM(NVTEVT_CB_MOVIE_REC_ONE_SEC,UIMenuWndWiFiMobileLink_OnMovieOneSec)
EVENT_END


void UIMenuWndWiFiModuleLink_UpdateData(void)
{
    static char buf1[32],buf2[32];
    char *pMacAddr;

    if(UI_GetData(FL_WIFI_LINK)==WIFI_LINK_OK)
    {
        if(UI_GetData(FL_NetWorkMode)==NETWORK_AP_MODE)
        {
            if(currentInfo.strSSID[0] == 0)
            {
                #if (MAC_APPEN_SSID==ENABLE)
                pMacAddr = (char*)UINet_GetMAC();
                sprintf(buf1,"SSID:%s% 02x%02x%02x%02x%02x%02x", UINet_GetSSID() ,pMacAddr[0], pMacAddr[1], pMacAddr[2]
                                                            ,pMacAddr[3], pMacAddr[4], pMacAddr[5]);
                #else
                sprintf(buf1,"SSID:%s",UINet_GetSSID());
                #endif
            }
            else
            {
                sprintf(buf1,"SSID:%s",currentInfo.strSSID);
            }


            sprintf(buf2,"PWA2:%s",UINet_GetPASSPHRASE());
	      debug_msg("ssid:%s\r\n",buf1);
	      debug_msg("key:%s\r\n",buf2);		  
            UxStatic_SetData(&UIMenuWndWiFiModuleLink_StaticTXT_SSIDCtrl,STATIC_VALUE,Txt_Pointer(buf1));
            UxStatic_SetData(&UIMenuWndWiFiModuleLink_StaticTXT_KeyCtrl,STATIC_VALUE,Txt_Pointer(buf2));
        }
    }
    else
    {
        sprintf(buf1,"%s:Fail",TXT_WIFI_CONNECT);
        UxStatic_SetData(&UIMenuWndWiFiModuleLink_StaticTXT_SSIDCtrl,STATIC_VALUE,Txt_Pointer(buf1));
        UxStatic_SetData(&UIMenuWndWiFiModuleLink_StaticTXT_KeyCtrl,STATIC_VALUE,STRID_NULL);
    }
}

static BOOL wifi_open = FALSE;
BOOL Getwifi_statue(void)
{
    return wifi_open;
}
void Setwifi_statue(BOOL Enb)
{
    wifi_open = Enb;
}
static UINT32  gUIMenuWndWiFiTimerID = NULL_TIMER;
INT32 UIMenuWndWiFiModuleLink_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	debug_msg("####   UIMenuWndWiFiModuleLink_OnOpen\r\n");
    UIMenuWndWiFiModuleLink_UpdateData();
    TurnOnWifiLed();
    if (gUIMenuWndWiFiTimerID==NULL_TIMER)
    {
        gUIMenuWndWiFiTimerID = GxTimer_StartTimer(TIMER_HALF_SEC, NVTEVT_05SEC_TIMER, CONTINUE);
    }
    //GxLED_SetCtrl(KEYSCAN_LED_RED,TURNON_LED,TRUE);
    UxTab_SetData(&UIMenuWndWiFiModeLink_Tab_RefreshAndWiFiOffCtrl, TAB_FOCUS, 0);
    //if (GxStrg_GetDeviceCtrl(0, CARD_INSERT))
    //Ux_PostEvent(NVTEVT_EXE_MOVIE_REC_START, 0);  
    Display_SetEnable(LAYER_VDO1, TRUE);
    UISound_EnableKey(TRUE);
    wifi_open = TRUE;
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    //Ux_PostEvent(NVTEVT_SYSTEM_MODE, 2, PRIMARY_MODE_MOVIE,SYS_SUBMODE_WIFI);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndWiFiModuleLink_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    wifi_open = FALSE;
TurnOffWifiLed();
 if (gUIMenuWndWiFiTimerID!=NULL_TIMER)
    {
        GxTimer_StopTimer(&gUIMenuWndWiFiTimerID);
    }
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}



INT32 UIMenuWndWiFiMobileLink_OnKeyUP(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32 uiKeyAct;
	
	 uiKeyAct = paramNum ? paramArray[0] : 0;

    switch (uiKeyAct)
    {
    case NVTEVT_KEY_PRESS:
        Display_SetEnable(LAYER_VDO1, FALSE);

		if(UI_GetData(FL_WIFI_LINK)==WIFI_LINK_OK)
            {   //change to normal mode for close app
            WifiApp_SendCmd(WIFIAPP_CMD_NOTIFY_STATUS, WIFIAPP_RET_DISCONNECT);
                WifiApp_SendCmd(WIFIAPP_CMD_NOTIFY_STATUS, WIFIAPP_RET_REMOVE_BY_USER);
                if (UIFlowWndWiFiMovie_GetStatus() == WIFI_MOV_ST_RECORD)
		{
		 FlowWiFiMovie_StopRec();
                if (GxStrg_GetDeviceCtrl(0, CARD_INSERT))
                FlowWiFiMovie_StartRec(WIFI_RTSP_REC);
                else
                FlowWiFiMovie_StartRec(WIFI_RTSP_LIVEVIEW);
		}
                
                {   
                    //change to normal mode for close app
                    Ux_PostEvent(NVTEVT_EXE_WIFI_STOP, 0);
                    Ux_PostEvent(NVTEVT_SYSTEM_MODE, 2, System_GetState(SYS_STATE_CURRMODE),SYS_SUBMODE_NORMAL);
                    //should close network application,then stop wifi
                    
                   // SetWIFI_PWR_Gpio(FALSE);
                }
#if 0
            if (UIFlowWndWiFiMovie_GetStatus() == WIFI_MOV_ST_RECORD)
		{
		
		 FlowWiFiMovie_StopRec();
               
		}
            TurnOffWifiLed();
            Setwifi_statue(FALSE);
            //GxLED_SetCtrl(KEYSCAN_LED_RED,TURNON_LED,FALSE);
            //should close network application,then stop wifi
                
                Ux_PostEvent(NVTEVT_SYSTEM_MODE, 2, System_GetState(SYS_STATE_CURRMODE),SYS_SUBMODE_NORMAL);
                Ux_PostEvent(NVTEVT_EXE_WIFI_STOP, 0);
         #endif       
            }
            else
            {                        
                Ux_CloseWindow(&UIMenuWndWiFiModuleLinkCtrl,0);
            }
            

		break;
    	}
				
			
    Ux_DefaultEvent(pCtrl,NVTEVT_KEY_SHUTTER2,paramNum,paramArray);
    return NVTEVT_CONSUME;
}


INT32 UIMenuWndWiFiMobileLink_OnKeyShutter2(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
return NVTEVT_CONSUME;
#if 0
	UINT32 uiKeyAct;
	INT32 curMode = System_GetState(SYS_STATE_CURRMODE);
	 uiKeyAct = paramNum ? paramArray[0] : 0;

    switch (uiKeyAct)
    {
    case NVTEVT_KEY_PRESS:
		if( curMode == PRIMARY_MODE_PHOTO)
			{
			debug_msg("###  key   press  start cap\r\n");
				return UIFlowWndWiFiPhoto_OnExePhotoCapture(pCtrl, paramNum, paramArray);
			}
		else if(curMode == PRIMARY_MODE_MOVIE)
			{
			
			 if (UIFlowWndWiFiMovie_GetStatus() == WIFI_MOV_ST_LVIEW)//if(!MediaRec_IsRecording())
				{
				debug_msg("###  key   press  start \r\n");
				paramNum = 1;
					paramArray[0]=1;
					return UIFlowWndWiFiMovie_OnExeMovieKeyRec(pCtrl, paramNum, paramArray);
				}
			else  if (UIFlowWndWiFiMovie_GetStatus() == WIFI_MOV_ST_RECORD)
				{
				debug_msg("###  key   press  stop\r\n");
				paramNum = 1;
					paramArray[0]=0;
				return UIFlowWndWiFiMovie_OnExeMovieKeyRec(pCtrl, paramNum, paramArray);
				}
				//return UIFlowWndWiFiMovie_OnExeMovieRec(pCtrl, paramNum, paramArray);
		
			}
		else if( curMode == PRIMARY_MODE_PLAYBACK)
				return NVTEVT_CONSUME;

		break;
    	}
				
			
    Ux_DefaultEvent(pCtrl,NVTEVT_KEY_SHUTTER2,paramNum,paramArray);
    return NVTEVT_CONSUME;
    #endif
}

INT32 UIMenuWndWiFiModuleLink_OnChildClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UIMenuWndWiFiModuleLink_UpdateData();
    Ux_DefaultEvent(pCtrl,NVTEVT_CHILD_CLOSE,paramNum,paramArray);
    if(UI_GetData(FL_WIFI_LINK)!=WIFI_LINK_OK)
    Ux_OpenWindow(&UIMenuWndWiFiMobileLinkOKCtrl,0);//show link fail
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndWiFiModuleLink_OnBattery(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndWiFiModuleLink_OnTimer(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
UINT32  uiEvent;
    uiEvent = paramNum ? paramArray[0] : 0;

    switch(uiEvent)
    { 
       
        case  NVTEVT_05SEC_TIMER:
            if(!MediaRec_IsRecording())
            {
            GxLED_SetCtrl(KEYSCAN_LED_GREEN,SET_TOGGLE_LED,FALSE);
            GxLED_SetCtrl(KEYSCAN_LED_GREEN,TURNON_LED,TRUE);
            }
            if (UIFlowWndWiFiMovie_GetStatus() == WIFI_MOV_ST_LVIEW)
		GxLED_SetCtrl(KEYSCAN_LED_GREEN,TURNON_LED,TRUE);
			break;
    }
	
    //Ux_DefaultEvent(pCtrl,NVTEVT_TIMER,paramNum,paramArray);
    return NVTEVT_CONSUME;
}

INT32 UIMenuWndWiFiMobileLink_OnGsensor(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
     if(g_bgsensor==FALSE)
     {
	g_bgsensor = TRUE;     
	debug_msg("%s..\r\n",__func__);
	MediaRec_SetCrash();
     }
    return NVTEVT_CONSUME;
}

INT32 UIMenuWndWiFiMobileLink_OnMovieOneSec(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return UIFlowWndWiFiMovie_OnMovieOneSec(pCtrl, paramNum, paramArray);
}
//----------------------UIMenuWndWiFiModuleLink_StaticICN_WiFiCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiModuleLink_StaticICN_WiFi)
EVENT_END

//----------------------UIMenuWndWiFiModuleLink_StaticICN_TitleBarCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiModuleLink_StaticICN_TitleBar)
EVENT_END

//----------------------UIMenuWndWiFiModuleLink_StatusTXT_WiFiModeCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiModuleLink_StatusTXT_WiFiMode)
EVENT_END

//----------------------UIMenuWndWiFiModuleLink_StaticTXT_SSIDCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiModuleLink_StaticTXT_SSID)
EVENT_END

//----------------------UIMenuWndWiFiModuleLink_StaticTXT_KeyCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiModuleLink_StaticTXT_Key)
EVENT_END

//----------------------UIMenuWndWiFiModeLink_Tab_RefreshAndWiFiOffCtrl Event---------------------------
INT32 UIMenuWndWiFiModeLink_Tab_RefreshAndWiFiOff_OnKeyLeft(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiModeLink_Tab_RefreshAndWiFiOff_OnKeyRight(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiModeLink_Tab_RefreshAndWiFiOff_OnKeyEnter(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiModeLink_Tab_Authorized_OK(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndWiFiModeLink_Tab_RefreshAndWiFiOff)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndWiFiModeLink_Tab_RefreshAndWiFiOff_OnKeyLeft)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndWiFiModeLink_Tab_RefreshAndWiFiOff_OnKeyRight)
EVENT_ITEM(NVTEVT_KEY_SHUTTER2,UIMenuWndWiFiModeLink_Tab_RefreshAndWiFiOff_OnKeyEnter)
EVENT_ITEM(NVTEVT_WIFI_AUTHORIZED_OK,UIMenuWndWiFiModeLink_Tab_Authorized_OK)
EVENT_END

INT32 UIMenuWndWiFiModeLink_Tab_RefreshAndWiFiOff_OnKeyLeft(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32 uiKeyAct;
	
	 uiKeyAct = paramNum ? paramArray[0] : 0;

    switch (uiKeyAct)
    {
    case NVTEVT_KEY_PRESS:
        Display_SetEnable(LAYER_VDO1, FALSE);

		if(UI_GetData(FL_WIFI_LINK)==WIFI_LINK_OK)
            {   //change to normal mode for close app
                WifiApp_SendCmd(WIFIAPP_CMD_NOTIFY_STATUS, WIFIAPP_RET_DISCONNECT);
                WifiApp_SendCmd(WIFIAPP_CMD_NOTIFY_STATUS, WIFIAPP_RET_REMOVE_BY_USER);
                if (UIFlowWndWiFiMovie_GetStatus() == WIFI_MOV_ST_RECORD)
		{
		 FlowWiFiMovie_StopRec();
         /*
                if (GxStrg_GetDeviceCtrl(0, CARD_INSERT))
                FlowWiFiMovie_StartRec(WIFI_RTSP_REC);
                else
                FlowWiFiMovie_StartRec(WIFI_RTSP_LIVEVIEW);
                */
		}
                
                {   //change to normal mode for close app
                    Ux_PostEvent(NVTEVT_EXE_WIFI_STOP, 0);
                    Ux_PostEvent(NVTEVT_SYSTEM_MODE, 2, System_GetState(SYS_STATE_CURRMODE),SYS_SUBMODE_NORMAL);
                    //should close network application,then stop wifi
                    
                   // SetWIFI_PWR_Gpio(FALSE);
                }
#if 0
            if (UIFlowWndWiFiMovie_GetStatus() == WIFI_MOV_ST_RECORD)
		{
		
		 FlowWiFiMovie_StopRec();
               
		}
            TurnOffWifiLed();
            Setwifi_statue(FALSE);
            //GxLED_SetCtrl(KEYSCAN_LED_RED,TURNON_LED,FALSE);
            //should close network application,then stop wifi
                
                Ux_PostEvent(NVTEVT_SYSTEM_MODE, 2, System_GetState(SYS_STATE_CURRMODE),SYS_SUBMODE_NORMAL);
                Ux_PostEvent(NVTEVT_EXE_WIFI_STOP, 0);
         #endif       
            }
            else
            {            
                Ux_CloseWindow(&UIMenuWndWiFiModuleLinkCtrl,0);
            }
            

		break;
    	}
				
#if 0
    UINT32  uiKeyAct;

    uiKeyAct = paramArray[0];
    switch(uiKeyAct)
    {
    case NVTEVT_KEY_PRESS:
        Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
        break;
    }
#endif
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndWiFiModeLink_Tab_RefreshAndWiFiOff_OnKeyRight(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32  uiKeyAct;

    uiKeyAct = paramArray[0];
    switch(uiKeyAct)
    {
    case NVTEVT_KEY_PRESS:
        Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
        break;
    }

    return NVTEVT_CONSUME;
}
INT32 UIMenuWndWiFiModeLink_Tab_RefreshAndWiFiOff_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32  uiKeyAct;

    uiKeyAct = paramArray[0];
    switch(uiKeyAct)
    {
    case NVTEVT_KEY_PRESS:
        switch(UxTab_GetData(&UIMenuWndWiFiModeLink_Tab_RefreshAndWiFiOffCtrl, TAB_FOCUS))
        {
        case UIMenuWndWiFiModeLink_Tab_RefreshAndWiFiOff_Button_Refresh:
            break;
        case UIMenuWndWiFiModeLink_Tab_RefreshAndWiFiOff_Button_WiFiOff:
            if(UIFlowWndWiFiMovie_GetStatus()==WIFI_MOV_ST_RECORD)
            {
                    debug_msg("stop movie record first..\r\n");
                    FlowWiFiMovie_StopRec();
            }
            if(UI_GetData(FL_WIFI_LINK)==WIFI_LINK_OK)
            {   //change to normal mode for close app
                Ux_PostEvent(NVTEVT_SYSTEM_MODE, 2, System_GetState(SYS_STATE_CURRMODE),SYS_SUBMODE_NORMAL);
                //should close network application,then stop wifi
                Ux_PostEvent(NVTEVT_EXE_WIFI_STOP, 0);
            }
            else 
            {
                Ux_CloseWindow(&UIMenuWndWiFiModuleLinkCtrl,0);
            }
            break;
        }
        break;
    }

    return NVTEVT_CONSUME;
}

INT32 UIMenuWndWiFiModeLink_Tab_Authorized_OK(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_OpenWindow(&UIMenuWndWiFiMobileLinkOKCtrl, 0);
    return NVTEVT_CONSUME;
}

//----------------------Button_RefreshCtrl Event---------------------------
EVENT_BEGIN(Button_Refresh)
EVENT_END

//----------------------Button_WiFiOffCtrl Event---------------------------
EVENT_BEGIN(Button_WiFiOff)
EVENT_END

INT32 UIMenuWndWiFiModuleLink_OnMovieFull(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return UIFlowWndWiFiMovie_OnMovieFull(pCtrl, paramNum, paramArray);
}
INT32 UIMenuWndWiFiModuleLink_OnMovieWrError(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return UIFlowWndWiFiMovie_OnMovieWrError(pCtrl, paramNum, paramArray);
}
INT32 UIMenuWndWiFiModuleLink_OnStorageSlow(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return UIFlowWndWiFiMovie_OnStorageSlow(pCtrl, paramNum, paramArray);
}
#endif

